### ISSUE TITLE
Segfaults after upgrade to Fedora 38

### ISSUE THREAD

**Issue by Tobias333** [ddterm/gnome-shell-extension-ddterm#413]
### GNOME Shell version

44.0

### Session type

Wayland (`echo $WAYLAND_DISPLAY` output is non-empty)

### Special configuration

- [ ] High DPI
- [X] More than one monitor

### ddterm version

44

### Linux distro

"Fedora Linux 38 (Workstation Edition)"

### ddterm settings dump

[/]
ddterm-toggle-hotkey=['F1']
palette=['rgb(23,20,33)', 'rgb(192,28,40)', 'rgb(38,162,105)', 'rgb(162,115,76)', 'rgb(18,72,139)', 'rgb(163,71,186)', 'rgb(42,161,179)', 'rgb(208,207,204)', 'rgb(94,92,100)', 'rgb(246,97,81)', 'rgb(51,218,122)', 'rgb(233,173,12)', 'rgb(42,123,222)', 'rgb(192,97,203)', 'rgb(51,199,222)', 'rgb(255,255,255)']
window-maximize=false

### Description

I have built the extension from Github according to the instructions. I can enable it, and I get the panel icon, but if I try to toggle the terminal per shortcut or panel icon, nothing happens. This is the error, according to journalctl /usr/bin/gnome-shell: 

Starting ddterm app: ["/home/USER/.local/share/gnome-shell/extensions/ddterm@amezin.github.com/com.github.amezin.ddterm","--undecorated","--gapplication-service"]
ddterm app killed by signal 11 (Segmentation fault)

**Comment by amezin** [comment]
It's weird that the test suite (usually) passes on Fedora 38 then.

Could you tell which exact commit you built the extension from? (I think I should add this info to the app somewhere...)

Does it happen every time?

**Comment by Tobias333** [comment]
Your commits from two days ago actually seem to have fixed this. I think they were the ones about removing RxJS. The extension currently seems to work without flaws. Happy to try out whatever may help. Amazing work that makes my life easier every single day!

**Comment by amezin** [comment]
> Your commits from two days ago actually seem to have fixed this. I think they were the ones about removing RxJS.

They shouldn't have any user-visible change. That's weird.

@noverby @IvanGrund @codesalatdev @by-cx @nurettin @skoobasteeve Does current `master` work for you or still crash?

**Comment by codesalatdev** [comment]
> > Your commits from two days ago actually seem to have fixed this. I think they were the ones about removing RxJS.
> 
> They shouldn't have any user-visible change. That's weird.
> 
> @noverby @IvanGrund @codesalatdev @by-cx @nurettin @skoobasteeve Does current `master` work for you or still crash?

A build from 0eee41adb742ef24d145d733a06a797fee462bf0 works for me :smile: :rocket:

**Comment by amezin** [comment]
It doesn't make sense.

I can't reproduce the crash on e54cd4b782ee7c02487ab98db631f005250f7500 (Apr 14) in Fedora 38 VM too.

I thought maybe the issue was caused by a bug in GJS, and then fixed by package updates - but it was last updated about a month ago.

**Comment by Tobias333** [comment]
May it be about interaction with Oh My Zsh or something shell related we may be using? I'm pretty positive it went away with the first commits that you have made two days ago. I didn't clear any preferences or sessions, just remove the extension and build from git. Before, the segfault came up every time. Since then not once.

**Comment by amezin** [comment]
Could you find the stack trace in journal output? It will likely be from gjs or gjs-console, not gnome-shell. Somewhere near "ddterm app killed by signal 11 (Segmentation fault)".
Could you find a core dump (coredumpctl)?

**Comment by codesalatdev** [comment]
> Could you find the stack trace in journal output? It will likely be from gjs or gjs-console, not gnome-shell. Somewhere near "ddterm app killed by signal 11 (Segmentation fault)". Could you find a core dump (coredumpctl)?

I still have a defunct version on another system of mine. It's based on commit 683ed271727c5128580db145ec3168a6fc1badc5 and produces the stacktrace attached:
[stacktrace.txt](https://github.com/ddterm/gnome-shell-extension-ddterm/files/11301458/stacktrace.txt)

I can also provide a coredump, tho I'd prefer sending that via a private channel

**Comment by amezin** [comment]
> I still have a defunct version on another system of mine. It's based on commit https://github.com/ddterm/gnome-shell-extension-ddterm/commit/683ed271727c5128580db145ec3168a6fc1badc5 and produces the stacktrace attached:

Not sure if coredumpctl resolves "Module ... from rpm ..." correctly, but if it does - everything seems to be at the latest version.

> I can also provide a coredump, tho I'd prefer sending that via a private channel

mezin.alexander@gmail.com

Does ddterm continue crashing if you restart GNOME Shell/reboot?

**Comment by Tobias333** [comment]
At the same timestamps that ddterm got the kill signal, there is this in the journal for gjs:

`Apr 14 16:28:30 fedora audit[40687]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=64 subj=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 pid=40687 comm="gjs" exe="/usr/bin/gjs-console" sig=11 res=1
Apr 14 16:28:30 fedora gjs[40687]: gtk_builder_extend_with_template: assertion 'buffer && buffer[0]' failed`

**Comment by codesalatdev** [comment]
> > I still have a defunct version on another system of mine. It's based on commit [683ed27](https://github.com/ddterm/gnome-shell-extension-ddterm/commit/683ed271727c5128580db145ec3168a6fc1badc5) and produces the stacktrace attached:
> 
> Not sure if coredumpctl resolves "Module ... from rpm ..." correctly, but if it does - everything seems to be at the latest version.

Just took a random sample and compared it to the package manager's info - everything seems to be reported correctly.

> > I can also provide a coredump, tho I'd prefer sending that via a private channel
> 
> [mezin.alexander@gmail.com](mailto:mezin.alexander@gmail.com)

Sent!

> Does ddterm continue crashing if you restart GNOME Shell/reboot?

Yes, it does.

**Comment by amezin** [comment]
Could you also archive and upload `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com`? ddterm doesn't save any user data or write logs in its source directory, so should be safe to upload here.

So far the only explanation I can think of is incomplete/damaged install (but then I'm curious how multiple people managed to do it at the same time).

**Comment by codesalatdev** [comment]
> Could you also archive and upload `~/.local/share/gnome-shell/extensions/ddterm@amezin.github.com`? ddterm doesn't save any user data or write logs in its source directory, so should be safe to upload here.
> 
> So far the only explanation I can think of is incomplete/damaged install (but then I'm curious how multiple people managed to do it at the same time).

[ddterm@amezin.github.com.zip](https://github.com/ddterm/gnome-shell-extension-ddterm/files/11301567/ddterm%40amezin.github.com.zip)

I still have my shell history and can see that I executed the same commands on the (now working) install. I don't know how `gnome-extensions install` handles overwriting already existing extensions, which is the only difference I can think of - despite the used commit.

**Comment by amezin** [comment]
`appwindow.ui` is empty. So something went wrong during either build or install.

**Comment by amezin** [comment]
I think I know how it happened.

`gtk-builder-tool` was not installed. So `make` failed, but the output file was created. Then when you ran `make` again after installing the missing dependencies, the file already existed, with a recent timestamp. So it was not rebuilt.

Not sure if it is worth fixing. Maybe I should add tool executables as dependencies, or set [`.DELETE_ON_ERROR`](https://www.gnu.org/software/make/manual/make.html#index-removing-targets-on-failure) in the `Makefile`, or output to temporary files first and then rename.

@codesalatdev @Tobias333 thanks for your help.
